OnlineJudge/OnlineJudge/urls.py
from django.contrib import admin
from django.urls import path
from OJ import views
from django.conf.urls.static import static
from django.conf import settings

# app_name = 'OJ'
# path('', include(('OJ.urls', 'OJ'), namespace='OJ'))
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.loginPage, name="Login"),
    path('logout/', views.logoutUser, name="Logout"),
    path('register/', views.Registration, name="Registration"),
    path('problems/', views.problemsList, name="Problems"),
    path('problems/<int:id>/', views.problemDetails, name="Details"),
    path('problems/<int:id>/code/', views.codeSubmission, name="Code"),
    path('problems/<int:id>/code/verdict/',
         views.judgeVerdict, name="Verdict"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

OnlineJudge/OJ/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
# from datetime import datetime


class Problem(models.Model):
    problemStatement = models.CharField(max_length=20000)
    problemName = models.CharField(max_length=500)
    problemDifficulty = models.CharField(max_length=100)


compiler_choices = (
    ('Select', 'Select your desired compiler'),
    ('GNU G++ 17', 'C++'),
    ('Java', 'Java'),
    ('Python 3', 'Python'),
)

class UserData(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    userEmail = models.EmailField(max_length=100)


class UserSubmission(models.Model):
    userCode = models.CharField(max_length=100000)
    compiler = models.CharField(
        max_length=50, choices=compiler_choices, default='Select')
    # verdict = models.CharField(max_length=300)
    submitted_at = models.DateTimeField("time of submission")
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    # def save(self, *args, **kwargs):
    #     now = timezone.now()
    #     self.submitted_at = now
    #     super(UserSubmission, self).save(*args, **kwargs)


class TestCase(models.Model):
    Input = models.CharField(max_length=1000, blank=True)
    Output = models.CharField(max_length=1000, blank=True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)

OnlineJudge/OJ/forms.py
from django import forms
from django.forms import ModelForm
from .models import Problem, UserSubmission, TestCase, UserData
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime

# class CodeSubmission(forms.Form):
#     # return HttpResponse("You are at the code submission page of problem %s" % problem_id)

#     # model = Problem
#     # context_object_name = 'problem'
#     # template_name = 'OJ/codeSubmission.html'
#     compiler = forms.Select()
#     userCode  = forms.CharField(label="Enter the code here", max_length = 10000)


class CodeSubmission(ModelForm):

    # def save(self, commit=True):
    #     send = super(CodeSubmission, self).save(commit=False)
    #     send.submitted_at = datetime.now()
    #     if commit:
    #         send.save()
    #     return send
    class Meta:
        model = UserSubmission
        fields = ['compiler', 'userCode']
        widgets = {
            'userCode': forms.Textarea(attrs={'class': '', 'rows': '22', 'cols': '128', 'data-val': 'true', 'data-val-required': 'Please enter your code here'})
        }


class RegistrationForm(ModelForm):

    class Meta:
        model = UserData
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'data-val': 'true', 'data-val-required': 'Please enter your user name'}),
            'password': forms.TextInput(attrs={'class': 'form-control', 'data-val': 'true', 'data-val-required': 'Please enter your password'}),
        }


class RegistrationForm2(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

OnlineJudge/OJ/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Problem, UserSubmission, TestCase, UserData
from django.views import generic
from django.urls import reverse
from django import forms
from .forms import CodeSubmission, RegistrationForm, RegistrationForm2
from django.views.decorators.csrf import csrf_protect, requires_csrf_token
from django.contrib.auth.forms import UserCreationForm
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .database_fetch import problem_number, compiler, user_code, input_test_cases, output_test_cases, latest_compiler
from .write_code import writeCpp, writeJava, writePython, writeCode
from .runCpp import cppMain, dockerCppMain
from .runPython import dockerPythonMain


# Create your views here.
''' Will have a view for 
    1. signup/login screen,
    2. problems list,
    3, problem details,
    4. submission of code,
    5. Judge verdict
'''


def Registration(request):
    if request.user.is_authenticated:
        return redirect('Problems')
    else:
        form = RegistrationForm2()
        if request.method == 'POST':
            form = RegistrationForm2(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, "Account was created for " + user)
                return redirect("Login")
        context = {'form': form}
        return render(request, 'OJ/registrationTemplate.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('Problems')
    else:
        context = {}
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('Problems')
            else:
                messages.info(
                    request, "The username-password combination does not exist")
                return redirect("Login")
        context = {}
        return render(request, "OJ/loginTemplate.html", context)


@login_required(login_url='Login')
def logoutUser(request):
    logout(request)
    return redirect('Login')


@login_required(login_url='Login')
def problemsList(request):
    try:
        problem_list = Problem.objects.order_by('problemDifficulty')
    except Problem.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'OJ/problemList.html', {'problem_list': problem_list})


@login_required(login_url='Login')
def problemDetails(request, id):
    problem = get_object_or_404(Problem, pk=id)
    return render(request, "OJ/problemDetails.html", {'problem': problem})


@login_required(login_url='Login')
def codeSubmission(request, id):
    problemOBJ = Problem.objects.get(id=id)
    form = CodeSubmission()
    if request.method == 'POST':
        form = CodeSubmission(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if instance.compiler == 'Select':
                messages.info(request, "Please select a compiler")
                return redirect('Code', id)
            elif instance.compiler == 'Java':
                messages.info(
                    request, "Sorry! Java functionality is currently not available. Please proceed with any other language.")
                return redirect('Code', id)
            else:
                instance.problem = problemOBJ
                instance.submitted_at = datetime.now()
                instance.user = request.user
                instance.save()
                return redirect("Verdict", id)
    context = {'form': form}
    return render(request, 'OJ/codeSubmission.html', context)


@login_required(login_url='Login')
def judgeVerdict(request, id):
    user_selected_compiler = latest_compiler(request.user.id)
    if user_selected_compiler == 'GNU G++ 17':
        writeCpp(request.user.id)
        your_fate = dockerCppMain(id)
    elif user_selected_compiler == 'Python 3':
        writePython(request.user.id)
        your_fate = dockerPythonMain(id)

    if your_fate == 1:
        return render(request, "OJ/judgeVerdictAccepted.html")
    elif your_fate == 0:
        return render(request, "OJ/judgeVerdictWrongAns.html")
    elif your_fate == -1:
        return render(request, "OJ/judgeVerdictCompilationError.html")

OnlineJudge/OJ/templates/OJ/codeSubmission.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>Submit your code</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit=no">


        <!-- <link rel="stylesheet" href="css/css/codeSubmission.css"> -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/codeSubmission.css' %}">
        <style>
            .CS-temp-text-input{
                display: none;
            }
            #id_userCode{
                display: none;
                padding: none;
                border: none;
                margin: none;
                cursor: none;
            }
        </style>
    </head>
    <body>
        {% include './navbar.html' %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="CS-all-parent">
                <div class="CS-compiler-select-parent">
                    <select id="compiler-select" name="compiler" class="form-select form-select-sm" aria-label=".form-select-sm">
                        <option selected value="Select">Select Compiler</option>
                        <option value="GNU G++ 17">GNU G++ 17.3.0</option>
                        <option value="Python 3">Python3</option>
                        <option value="Java">Java</option>
                    </select>
                </div>
                <div class="CS-error-message">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}</p>
                </div>
                <div class="CS-theme-selector-parent">
                    <div class="btn-group CS-theme-selector">
                        <button type="button" class="btn btn-sm btn-info dropdown-toggle CS-theme-selector" data-bs-toggle="dropdown" aria-expanded="false">
                        Theme
                        </button>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" onclick="theme('tomorrow')" href="#">tomorrow</a></li>
                        <li><a class="dropdown-item" onclick="theme('twilight')" href="#">twilight</a></li>
                        <li><a class="dropdown-item" onclick="theme('monokai')" href="#">monokai</a></li>
                        </ul>
                    </div>
                </div> 
                <div class="CS-size-selector-parent">
                    <div class="btn-group CS-size-selector">
                        <button type="button" class="btn btn-sm btn-warning dropdown-toggle CS-size-selector" data-bs-toggle="dropdown" aria-expanded="false">
                        Size
                        </button>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" onclick="size('14px')" value="14" href="#">14</a></li>
                        <li><a class="dropdown-item" onclick="size('16px')" value="16" href="#">16</a></li>
                        <li><a class="dropdown-item" onclick="size('18px')" value="18" href="#">18</a></li>
                        </ul>
                    </div>
                </div>
                </div>

                <div class="CS-editor-parent">
                    <div type="text" id="editor"></div>
                </div>
            

                <!-- <div class="django-ace-widget ace_editor ace_hidpi ace_dark ace-monokai" style="" maxlength="10000" required_id="id_userCode">
                        <p id="fontcolor">Write your code here:</p>
                    </div> -->
                    <div class="CS-submit-button-parent">
                        <input class="btn btn-success" onclick="submit()" type="submit" value="Submit">
                        <div class="CS-temp-text-input">
                            {{ form.userCode }}
                        </div>
                    </div>
        </form>

        <!-- The below lines should be in order only because otherwise codeSubmission.js will look for the output from ace.js which will not be present and hence, the real output won't be correct. -->
        <script rel="javascript" src="{% static 'ace-builds/src-noconflict/ace.js' %}" type="text/javascript" charset="utf-8"></script>   
        <script rel="javascript" src="{% static 'js/codeSubmission.js' %}"></script>
        <!-- <script src="ace/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script> -->
        <!-- <script src="js/js/codeSubmission.js"></script> -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    </body>
</html>

OnlineJudge/OJ/templates/OJ/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- <title>Hello, world!</title> -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    <!-- <h1>Hello, world!</h1> -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

OnlineJudge/OJ/templates/OJ/judgeVerdict.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Verdict</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Verdict</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<div>
                        <!-- {% csrf_token %} -->
						<!-- <div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div> -->

                        <h2>Accepted!</h2>

					</div>
				</div>
				
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

OnlineJudge/OJ/templates/OJ/judgeVerdictAccepted.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Verdict</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Verdict</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<div>
                        <!-- {% csrf_token %} -->
						<!-- <div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div> -->

                        <h2>Accepted!</h2>

					</div>
				</div>
				
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

OnlineJudge/OJ/templates/OJ/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<nav class="navbar-nav">
  <!-- <img class="navbar-logo" src="static 'images/logo.png" alt="logo"> -->
  <div class="navbar-logo"></div>
  <ul class="navbar-ul" style="margin: 0px;">
    <li class="hello-msg">Hello, {{ request.user }}</li>
    <li><a class="navbar-logout" href="{% url 'Logout' %}">Logout</a></li>
  </ul>
</nav>

OnlineJudge/OJ/templates/OJ/problemDetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ problem.problemName }}</title>
    <!-- <link rel="stylesheet" href="css/css/problemDetails.css"> -->
    <!-- <link rel="stylesheet" href="css/css/utilities.css"> -->
    <link rel="stylesheet" href="{% static 'css/utilities.css' %}">
    <link rel="stylesheet" href="{% static 'css/problemDetails.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body class="PD-body">
    {% include './navbar.html' %}
    <div id="problem-name" class="PD-problem-name-heading font-style-dancing-script" target={{ problem.problemDifficulty }}>{{ problem.problemName }}</div>
        <div id="problem-statement" class="PD-problem-statement font-style-hind">{{ problem.problemStatement }}</div>
    <div class="PD-button-parent">
        <a role="button" type="button" id="btn" class="btn btn-outline-light" href="{% url 'Code' problem.id %}">Go to code editor</a>
    </div>

    <!-- <script src="js/js/problemDetails.js" type="javascript"></script> -->
    <script src="{% static 'js/problemDetails.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>
</body>
</html>